spring.datasource.url: jdbc:mysql://localhost:3306/weather_info?useSSL=false
spring.datasource.username: root
spring.datasource.password: 11111111
spring.jpa.hibernate.use-new-id-generator-mappings: false

location: Minsk

updateInterval: PT012H
